# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='hold_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
