# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationtype',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
