# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20170618_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='hold_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
