# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20170610_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='tables',
        ),
    ]
