# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_auto_20170609_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='contact_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='building_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
