# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_remove_building_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
