# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_remove_reservation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_types',
            new_name='reservation_type',
        ),
    ]
